Clean up "publish-unit-test-results-via-xray" and "publish-integration-test-results-via-xray" commands, add cucumber step

diff --git a/microservices.yml b/microservices.yml
--- a/microservices.yml
+++ b/microservices.yml
@@ -455,14 +455,8 @@ commands:
     description: Publish all unit test results to Jira Xray
     steps:
       - run:
-          name: Download publish to Xray script
-          when: always
-          command: |
-            # get push-test-results-to-xray.sh
-             wget https://raw.githubusercontent.com/MGMDV-Orbs/microservices/f/xray-r2.3/.circleci/push-test-results-to-xray.sh -O push-test-results-to-xray.sh
-      - run:
           name: Upload Mocha unit test results to Jira Xray
-          when: on_success
+          when: always
           command: |
             SERVICE_DIR=/home/circleci/project
             CIRCLE_SHA1=$(cd $SERVICE_DIR && git rev-parse HEAD)
@@ -492,19 +486,45 @@ commands:
               --data @"$TEST_RESULTS_FILE"
             )
             echo "UPLOAD RESULT = $RESULTS_TEST"
+      - run:
+          name: Upload Cucumber unit test results to Jira Xray
+          when: always
+          command: |
+            SERVICE_DIR=/home/circleci/project
+            CIRCLE_SHA1=$(cd $SERVICE_DIR && git rev-parse HEAD)
+            TEST_RESULTS_FILE=./reports/unit-tests-output.xml
+            PROJECT_CODE=SRV
+            TEST_TYPE=junit
+            echo "Push Xray Version 1.0.1"
+            echo "File to process: $TEST_RESULTS_FILE"
+            echo "Jira Project Name: $PROJECT_CODE"
+            echo "Test Type: $TEST_TYPE"
+            echo "CIRCLE_SHA1 = $CIRCLE_SHA1"
+            echo "Project Path: $SERVICE_DIR"
+            if ! test -f $TEST_RESULTS_FILE; then
+              echo "cucumber test results file not found ($TEST_RESULTS_FILE)"
+              exit 1
+            fi
+            XRAY_AUTH_TOKEN=$(\
+              curl -s https://xray.cloud.xpand-it.com/api/v1/authenticate \
+                -H "Content-Type: application/json" -X POST \
+                --data "{ \"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\" }" \
+                | tr -d '"'
+            )
+            RESULTS_TEST=$(\curl "https://xray.cloud.xpand-it.com/api/v1/import/execution/junit?projectKey=$PROJECT_CODE&revision=$CIRCLE_SHA1" \
+              -H "Content-Type: text/xml" \
+              -X POST \
+              -H "Authorization: Bearer $XRAY_AUTH_TOKEN" \
+              --data @"$TEST_RESULTS_FILE"
+            )
+            echo "UPLOAD RESULT = $RESULTS_TEST"
 
   publish-integration-test-results-via-xray:
     description: Publish all integration test results to Jira Xray
     steps:
       - run:
-          name: Download publish to Xray script
-          when: always
-          command: |
-            # get push-test-results-to-xray.sh
-             wget https://raw.githubusercontent.com/MGMDV-Orbs/microservices/f/xray-r2.3/.circleci/push-test-results-to-xray.sh -O push-test-results-to-xray.sh
-      - run:
           name: Upload Mocha integration test results to Jira Xray
-          when: on_success
+          when: always
           command: |
             SERVICE_DIR=/home/circleci/project
             CIRCLE_SHA1=$(cd $SERVICE_DIR && git rev-parse HEAD)
@@ -519,6 +539,38 @@ commands:
             echo "Project Path: $SERVICE_DIR"
             if ! test -f $TEST_RESULTS_FILE; then
               echo "mocha test results file not found ($TEST_RESULTS_FILE)"
+              exit 1
+            fi
+            XRAY_AUTH_TOKEN=$(\
+              curl -s https://xray.cloud.xpand-it.com/api/v1/authenticate \
+                -H "Content-Type: application/json" -X POST \
+                --data "{ \"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\" }" \
+                | tr -d '"'
+            )
+            RESULTS_TEST=$(\curl "https://xray.cloud.xpand-it.com/api/v1/import/execution/junit?projectKey=$PROJECT_CODE&revision=$CIRCLE_SHA1" \
+              -H "Content-Type: text/xml" \
+              -X POST \
+              -H "Authorization: Bearer $XRAY_AUTH_TOKEN" \
+              --data @"$TEST_RESULTS_FILE"
+            )
+            echo "UPLOAD RESULT = $RESULTS_TEST"
+      - run:
+          name: Upload Cucumber integration test results to Jira Xray
+          when: always
+          command: |
+            SERVICE_DIR=/home/circleci/project
+            CIRCLE_SHA1=$(cd $SERVICE_DIR && git rev-parse HEAD)
+            TEST_RESULTS_FILE=./reports/integration-tests-output.xml
+            PROJECT_CODE=SRV
+            TEST_TYPE=junit
+            echo "Push Xray Version 1.0.1"
+            echo "File to process: $TEST_RESULTS_FILE"
+            echo "Jira Project Name: $PROJECT_CODE"
+            echo "Test Type: $TEST_TYPE"
+            echo "CIRCLE_SHA1 = $CIRCLE_SHA1"
+            echo "Project Path: $SERVICE_DIR"
+            if ! test -f $TEST_RESULTS_FILE; then
+              echo "cucumber test results file not found ($TEST_RESULTS_FILE)"
               exit 1
             fi
             XRAY_AUTH_TOKEN=$(\
