Needs executor

diff --git a/microservices.yml b/microservices.yml
--- a/microservices.yml
+++ b/microservices.yml
@@ -4,142 +4,6 @@ orbs:
   vpn: mgmorbs/vpn@1
 
 commands:
-  publish-unit-test-results-via-xray:
-    description: Publish all unit test results to Jira Xray
-    steps:
-      - run:
-          name: Upload Mocha unit test results to Jira Xray
-          when: always
-          command: |
-            SERVICE_DIR=/home/circleci/project
-            CIRCLE_SHA1=$(cd $SERVICE_DIR && git rev-parse HEAD)
-            TEST_RESULTS_FILE=./reports/unit-test-mocha-results.xml
-            PROJECT_CODE=SRV
-            TEST_TYPE=junit
-            echo "Push Xray Version 1.0.1"
-            echo "File to process: $TEST_RESULTS_FILE"
-            echo "Jira Project Name: $PROJECT_CODE"
-            echo "Test Type: $TEST_TYPE"
-            echo "CIRCLE_SHA1 = $CIRCLE_SHA1"
-            echo "Project Path: $SERVICE_DIR"
-            if ! test -f $TEST_RESULTS_FILE; then
-              echo "mocha test results file not found ($TEST_RESULTS_FILE)"
-              exit 1
-            fi
-            XRAY_AUTH_TOKEN=$(\
-              curl -s https://xray.cloud.xpand-it.com/api/v1/authenticate \
-                -H "Content-Type: application/json" -X POST \
-                --data "{ \"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\" }" \
-                | tr -d '"'
-            )
-            RESULTS_TEST=$(\curl "https://xray.cloud.xpand-it.com/api/v1/import/execution/junit?projectKey=$PROJECT_CODE&revision=$CIRCLE_SHA1" \
-              -H "Content-Type: text/xml" \
-              -X POST \
-              -H "Authorization: Bearer $XRAY_AUTH_TOKEN" \
-              --data @"$TEST_RESULTS_FILE"
-            )
-            echo "UPLOAD RESULT = $RESULTS_TEST"
-      - run:
-          name: Upload Cucumber unit test results to Jira Xray
-          when: always
-          command: |
-            SERVICE_DIR=/home/circleci/project
-            CIRCLE_SHA1=$(cd $SERVICE_DIR && git rev-parse HEAD)
-            TEST_RESULTS_FILE=./reports/unit-test-results.json
-            PROJECT_CODE=SRV
-            TEST_TYPE=cucumber
-            echo "Push Xray Version 1.0.1"
-            echo "File to process: $TEST_RESULTS_FILE"
-            echo "Jira Project Name: $PROJECT_CODE"
-            echo "Test Type: $TEST_TYPE"
-            echo "CIRCLE_SHA1 = $CIRCLE_SHA1"
-            echo "Project Path: $SERVICE_DIR"
-            if ! test -f $TEST_RESULTS_FILE; then
-              echo "cucumber test results file not found ($TEST_RESULTS_FILE)"
-              exit 1
-            fi
-            XRAY_AUTH_TOKEN=$(\
-              curl -s https://xray.cloud.xpand-it.com/api/v1/authenticate \
-                -H "Content-Type: application/json" -X POST \
-                --data "{ \"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\" }" \
-                | tr -d '"'
-            )
-            RESULTS_TEST=$(\curl "https://xray.cloud.xpand-it.com/api/v1/import/execution/cucumber" \
-              -H "Content-Type: text/xml" \
-              -X POST \
-              -H "Authorization: Bearer $XRAY_AUTH_TOKEN" \
-              --data @"$TEST_RESULTS_FILE"
-            )
-            echo "UPLOAD RESULT = $RESULTS_TEST"
-
-  publish-integration-test-results-via-xray:
-    description: Publish all integration test results to Jira Xray
-    steps:
-      - run:
-          name: Upload Mocha integration test results to Jira Xray
-          when: always
-          command: |
-            SERVICE_DIR=/home/circleci/project
-            CIRCLE_SHA1=$(cd $SERVICE_DIR && git rev-parse HEAD)
-            TEST_RESULTS_FILE=./reports/integration-test-mocha-results.xml
-            PROJECT_CODE=SRV
-            TEST_TYPE=junit
-            echo "Push Xray Version 1.0.1"
-            echo "File to process: $TEST_RESULTS_FILE"
-            echo "Jira Project Name: $PROJECT_CODE"
-            echo "Test Type: $TEST_TYPE"
-            echo "CIRCLE_SHA1 = $CIRCLE_SHA1"
-            echo "Project Path: $SERVICE_DIR"
-            if ! test -f $TEST_RESULTS_FILE; then
-              echo "mocha test results file not found ($TEST_RESULTS_FILE)"
-              exit 1
-            fi
-            XRAY_AUTH_TOKEN=$(\
-              curl -s https://xray.cloud.xpand-it.com/api/v1/authenticate \
-                -H "Content-Type: application/json" -X POST \
-                --data "{ \"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\" }" \
-                | tr -d '"'
-            )
-            RESULTS_TEST=$(\curl "https://xray.cloud.xpand-it.com/api/v1/import/execution/junit?projectKey=$PROJECT_CODE&revision=$CIRCLE_SHA1" \
-              -H "Content-Type: text/xml" \
-              -X POST \
-              -H "Authorization: Bearer $XRAY_AUTH_TOKEN" \
-              --data @"$TEST_RESULTS_FILE"
-            )
-            echo "UPLOAD RESULT = $RESULTS_TEST"
-      - run:
-          name: Upload Cucumber integration test results to Jira Xray
-          when: always
-          command: |
-            SERVICE_DIR=/home/circleci/project
-            CIRCLE_SHA1=$(cd $SERVICE_DIR && git rev-parse HEAD)
-            TEST_RESULTS_FILE=./reports/integration-test-results.json
-            PROJECT_CODE=SRV
-            TEST_TYPE=cucumber
-            echo "Push Xray Version 1.0.1"
-            echo "File to process: $TEST_RESULTS_FILE"
-            echo "Jira Project Name: $PROJECT_CODE"
-            echo "Test Type: $TEST_TYPE"
-            echo "CIRCLE_SHA1 = $CIRCLE_SHA1"
-            echo "Project Path: $SERVICE_DIR"
-            if ! test -f $TEST_RESULTS_FILE; then
-              echo "cucumber test results file not found ($TEST_RESULTS_FILE)"
-              exit 1
-            fi
-            XRAY_AUTH_TOKEN=$(\
-              curl -s https://xray.cloud.xpand-it.com/api/v1/authenticate \
-                -H "Content-Type: application/json" -X POST \
-                --data "{ \"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\" }" \
-                | tr -d '"'
-            )
-            RESULTS_TEST=$(\curl "https://xray.cloud.xpand-it.com/api/v1/import/execution/cucumber" \
-              -H "Content-Type: text/xml" \
-              -X POST \
-              -H "Authorization: Bearer $XRAY_AUTH_TOKEN" \
-              --data @"$TEST_RESULTS_FILE"
-            )
-            echo "UPLOAD RESULT = $RESULTS_TEST"
-
   print-diagnostics:
     description: Prints diagnostic information about current build environment
     steps:
@@ -587,6 +451,142 @@ commands:
             # run dangerfile
             ./node_modules/.bin/danger ci --failOnErrors
 
+  publish-unit-test-results-via-xray:
+    description: Publish all unit test results to Jira Xray
+    steps:
+      - run:
+          name: Upload Mocha unit test results to Jira Xray
+          when: always
+          command: |
+            SERVICE_DIR=/home/circleci/project
+            CIRCLE_SHA1=$(cd $SERVICE_DIR && git rev-parse HEAD)
+            TEST_RESULTS_FILE=./reports/unit-test-mocha-results.xml
+            PROJECT_CODE=SRV
+            TEST_TYPE=junit
+            echo "Push Xray Version 1.0.1"
+            echo "File to process: $TEST_RESULTS_FILE"
+            echo "Jira Project Name: $PROJECT_CODE"
+            echo "Test Type: $TEST_TYPE"
+            echo "CIRCLE_SHA1 = $CIRCLE_SHA1"
+            echo "Project Path: $SERVICE_DIR"
+            if ! test -f $TEST_RESULTS_FILE; then
+              echo "mocha test results file not found ($TEST_RESULTS_FILE)"
+              exit 1
+            fi
+            XRAY_AUTH_TOKEN=$(\
+              curl -s https://xray.cloud.xpand-it.com/api/v1/authenticate \
+                -H "Content-Type: application/json" -X POST \
+                --data "{ \"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\" }" \
+                | tr -d '"'
+            )
+            RESULTS_TEST=$(\curl "https://xray.cloud.xpand-it.com/api/v1/import/execution/junit?projectKey=$PROJECT_CODE&revision=$CIRCLE_SHA1" \
+              -H "Content-Type: text/xml" \
+              -X POST \
+              -H "Authorization: Bearer $XRAY_AUTH_TOKEN" \
+              --data @"$TEST_RESULTS_FILE"
+            )
+            echo "UPLOAD RESULT = $RESULTS_TEST"
+      - run:
+          name: Upload Cucumber unit test results to Jira Xray
+          when: always
+          command: |
+            SERVICE_DIR=/home/circleci/project
+            CIRCLE_SHA1=$(cd $SERVICE_DIR && git rev-parse HEAD)
+            TEST_RESULTS_FILE=./reports/unit-test-results.json
+            PROJECT_CODE=SRV
+            TEST_TYPE=cucumber
+            echo "Push Xray Version 1.0.1"
+            echo "File to process: $TEST_RESULTS_FILE"
+            echo "Jira Project Name: $PROJECT_CODE"
+            echo "Test Type: $TEST_TYPE"
+            echo "CIRCLE_SHA1 = $CIRCLE_SHA1"
+            echo "Project Path: $SERVICE_DIR"
+            if ! test -f $TEST_RESULTS_FILE; then
+              echo "cucumber test results file not found ($TEST_RESULTS_FILE)"
+              exit 1
+            fi
+            XRAY_AUTH_TOKEN=$(\
+              curl -s https://xray.cloud.xpand-it.com/api/v1/authenticate \
+                -H "Content-Type: application/json" -X POST \
+                --data "{ \"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\" }" \
+                | tr -d '"'
+            )
+            RESULTS_TEST=$(\curl "https://xray.cloud.xpand-it.com/api/v1/import/execution/cucumber" \
+              -H "Content-Type: text/xml" \
+              -X POST \
+              -H "Authorization: Bearer $XRAY_AUTH_TOKEN" \
+              --data @"$TEST_RESULTS_FILE"
+            )
+            echo "UPLOAD RESULT = $RESULTS_TEST"
+
+  publish-integration-test-results-via-xray:
+    description: Publish all integration test results to Jira Xray
+    steps:
+      - run:
+          name: Upload Mocha integration test results to Jira Xray
+          when: always
+          command: |
+            SERVICE_DIR=/home/circleci/project
+            CIRCLE_SHA1=$(cd $SERVICE_DIR && git rev-parse HEAD)
+            TEST_RESULTS_FILE=./reports/integration-test-mocha-results.xml
+            PROJECT_CODE=SRV
+            TEST_TYPE=junit
+            echo "Push Xray Version 1.0.1"
+            echo "File to process: $TEST_RESULTS_FILE"
+            echo "Jira Project Name: $PROJECT_CODE"
+            echo "Test Type: $TEST_TYPE"
+            echo "CIRCLE_SHA1 = $CIRCLE_SHA1"
+            echo "Project Path: $SERVICE_DIR"
+            if ! test -f $TEST_RESULTS_FILE; then
+              echo "mocha test results file not found ($TEST_RESULTS_FILE)"
+              exit 1
+            fi
+            XRAY_AUTH_TOKEN=$(\
+              curl -s https://xray.cloud.xpand-it.com/api/v1/authenticate \
+                -H "Content-Type: application/json" -X POST \
+                --data "{ \"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\" }" \
+                | tr -d '"'
+            )
+            RESULTS_TEST=$(\curl "https://xray.cloud.xpand-it.com/api/v1/import/execution/junit?projectKey=$PROJECT_CODE&revision=$CIRCLE_SHA1" \
+              -H "Content-Type: text/xml" \
+              -X POST \
+              -H "Authorization: Bearer $XRAY_AUTH_TOKEN" \
+              --data @"$TEST_RESULTS_FILE"
+            )
+            echo "UPLOAD RESULT = $RESULTS_TEST"
+      - run:
+          name: Upload Cucumber integration test results to Jira Xray
+          when: always
+          command: |
+            SERVICE_DIR=/home/circleci/project
+            CIRCLE_SHA1=$(cd $SERVICE_DIR && git rev-parse HEAD)
+            TEST_RESULTS_FILE=./reports/integration-test-results.json
+            PROJECT_CODE=SRV
+            TEST_TYPE=cucumber
+            echo "Push Xray Version 1.0.1"
+            echo "File to process: $TEST_RESULTS_FILE"
+            echo "Jira Project Name: $PROJECT_CODE"
+            echo "Test Type: $TEST_TYPE"
+            echo "CIRCLE_SHA1 = $CIRCLE_SHA1"
+            echo "Project Path: $SERVICE_DIR"
+            if ! test -f $TEST_RESULTS_FILE; then
+              echo "cucumber test results file not found ($TEST_RESULTS_FILE)"
+              exit 1
+            fi
+            XRAY_AUTH_TOKEN=$(\
+              curl -s https://xray.cloud.xpand-it.com/api/v1/authenticate \
+                -H "Content-Type: application/json" -X POST \
+                --data "{ \"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\" }" \
+                | tr -d '"'
+            )
+            RESULTS_TEST=$(\curl "https://xray.cloud.xpand-it.com/api/v1/import/execution/cucumber" \
+              -H "Content-Type: text/xml" \
+              -X POST \
+              -H "Authorization: Bearer $XRAY_AUTH_TOKEN" \
+              --data @"$TEST_RESULTS_FILE"
+            )
+            echo "UPLOAD RESULT = $RESULTS_TEST"
+
 jobs:
   publish-aws-lambdas:
     executor: vpn/aws
@@ -663,8 +663,9 @@ jobs:
             - run-unit-tests-in-docker
 
   publish-unit-test-results-to-xray:
+    executor: vpn/aws
     steps:
-      - publish-unit-test-results-via-xray
+    - publish-unit-test-results-via-xray
 
   # Step 3b: Verify that integration tests are passing
   run-integration-tests:
@@ -679,8 +680,9 @@ jobs:
             - run-integration-tests-in-docker
 
   publish-integration-test-results-to-xray:
+    executor: vpn/aws
     steps:
-      - publish-integration-test-results-via-xray
+    - publish-integration-test-results-via-xray
 
   # Step 3c: Verify that lint is passing
   run-lint:
